// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhI4CDb8ehzChmeY5GzkFxMPiVEpN5bi0',
    appId: '1:68304888188:web:5c33ebd20474e5cd1604f9',
    messagingSenderId: '68304888188',
    projectId: 'studentline-de',
    authDomain: 'studentline-de.firebaseapp.com',
    storageBucket: 'studentline-de.appspot.com',
    measurementId: 'G-K57100168B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAYJKVVzXpLzLHsjrPdRwDP-kvELNcubU',
    appId: '1:68304888188:android:fe92ec15acc5a1c91604f9',
    messagingSenderId: '68304888188',
    projectId: 'studentline-de',
    storageBucket: 'studentline-de.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDvcJsg91Iu6GmDpe-kxYqLF1YDSVWD_w',
    appId: '1:68304888188:ios:0fcd0e68b8c1549e1604f9',
    messagingSenderId: '68304888188',
    projectId: 'studentline-de',
    storageBucket: 'studentline-de.appspot.com',
    iosBundleId: 'com.example.flutterBasics',
  );
}
